/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as MainLayoutSpaceSpaceIdIndexRouteImport } from './routes/_mainLayout/space/$spaceId/index'
import { Route as MainLayoutJoinInviteIdIndexRouteImport } from './routes/_mainLayout/join/$inviteId/index'
import { Route as MainLayoutDmRoomIdIndexRouteImport } from './routes/_mainLayout/dm/$roomId/index'
import { Route as MainLayoutSpaceSpaceIdRoomIndexRouteImport } from './routes/_mainLayout/space/$spaceId/room/index'
import { Route as MainLayoutSpaceSpaceIdRoomRoomIdIndexRouteImport } from './routes/_mainLayout/space/$spaceId/room/$roomId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSpaceSpaceIdIndexRoute =
  MainLayoutSpaceSpaceIdIndexRouteImport.update({
    id: '/space/$spaceId/',
    path: '/space/$spaceId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutJoinInviteIdIndexRoute =
  MainLayoutJoinInviteIdIndexRouteImport.update({
    id: '/join/$inviteId/',
    path: '/join/$inviteId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutDmRoomIdIndexRoute = MainLayoutDmRoomIdIndexRouteImport.update({
  id: '/dm/$roomId/',
  path: '/dm/$roomId/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSpaceSpaceIdRoomIndexRoute =
  MainLayoutSpaceSpaceIdRoomIndexRouteImport.update({
    id: '/space/$spaceId/room/',
    path: '/space/$spaceId/room/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute =
  MainLayoutSpaceSpaceIdRoomRoomIdIndexRouteImport.update({
    id: '/space/$spaceId/room/$roomId/',
    path: '/space/$spaceId/room/$roomId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/login': typeof LoginRoute
  '/dm/$roomId/': typeof MainLayoutDmRoomIdIndexRoute
  '/join/$inviteId/': typeof MainLayoutJoinInviteIdIndexRoute
  '/space/$spaceId/': typeof MainLayoutSpaceSpaceIdIndexRoute
  '/space/$spaceId/room/': typeof MainLayoutSpaceSpaceIdRoomIndexRoute
  '/space/$spaceId/room/$roomId/': typeof MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof MainLayoutIndexRoute
  '/dm/$roomId': typeof MainLayoutDmRoomIdIndexRoute
  '/join/$inviteId': typeof MainLayoutJoinInviteIdIndexRoute
  '/space/$spaceId': typeof MainLayoutSpaceSpaceIdIndexRoute
  '/space/$spaceId/room': typeof MainLayoutSpaceSpaceIdRoomIndexRoute
  '/space/$spaceId/room/$roomId': typeof MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/_mainLayout/dm/$roomId/': typeof MainLayoutDmRoomIdIndexRoute
  '/_mainLayout/join/$inviteId/': typeof MainLayoutJoinInviteIdIndexRoute
  '/_mainLayout/space/$spaceId/': typeof MainLayoutSpaceSpaceIdIndexRoute
  '/_mainLayout/space/$spaceId/room/': typeof MainLayoutSpaceSpaceIdRoomIndexRoute
  '/_mainLayout/space/$spaceId/room/$roomId/': typeof MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dm/$roomId/'
    | '/join/$inviteId/'
    | '/space/$spaceId/'
    | '/space/$spaceId/room/'
    | '/space/$spaceId/room/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/dm/$roomId'
    | '/join/$inviteId'
    | '/space/$spaceId'
    | '/space/$spaceId/room'
    | '/space/$spaceId/room/$roomId'
  id:
    | '__root__'
    | '/_mainLayout'
    | '/login'
    | '/_mainLayout/'
    | '/_mainLayout/dm/$roomId/'
    | '/_mainLayout/join/$inviteId/'
    | '/_mainLayout/space/$spaceId/'
    | '/_mainLayout/space/$spaceId/room/'
    | '/_mainLayout/space/$spaceId/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/space/$spaceId/': {
      id: '/_mainLayout/space/$spaceId/'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId/'
      preLoaderRoute: typeof MainLayoutSpaceSpaceIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/join/$inviteId/': {
      id: '/_mainLayout/join/$inviteId/'
      path: '/join/$inviteId'
      fullPath: '/join/$inviteId/'
      preLoaderRoute: typeof MainLayoutJoinInviteIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/dm/$roomId/': {
      id: '/_mainLayout/dm/$roomId/'
      path: '/dm/$roomId'
      fullPath: '/dm/$roomId/'
      preLoaderRoute: typeof MainLayoutDmRoomIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/space/$spaceId/room/': {
      id: '/_mainLayout/space/$spaceId/room/'
      path: '/space/$spaceId/room'
      fullPath: '/space/$spaceId/room/'
      preLoaderRoute: typeof MainLayoutSpaceSpaceIdRoomIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/space/$spaceId/room/$roomId/': {
      id: '/_mainLayout/space/$spaceId/room/$roomId/'
      path: '/space/$spaceId/room/$roomId'
      fullPath: '/space/$spaceId/room/$roomId/'
      preLoaderRoute: typeof MainLayoutSpaceSpaceIdRoomRoomIdIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutDmRoomIdIndexRoute: typeof MainLayoutDmRoomIdIndexRoute
  MainLayoutJoinInviteIdIndexRoute: typeof MainLayoutJoinInviteIdIndexRoute
  MainLayoutSpaceSpaceIdIndexRoute: typeof MainLayoutSpaceSpaceIdIndexRoute
  MainLayoutSpaceSpaceIdRoomIndexRoute: typeof MainLayoutSpaceSpaceIdRoomIndexRoute
  MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute: typeof MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutDmRoomIdIndexRoute: MainLayoutDmRoomIdIndexRoute,
  MainLayoutJoinInviteIdIndexRoute: MainLayoutJoinInviteIdIndexRoute,
  MainLayoutSpaceSpaceIdIndexRoute: MainLayoutSpaceSpaceIdIndexRoute,
  MainLayoutSpaceSpaceIdRoomIndexRoute: MainLayoutSpaceSpaceIdRoomIndexRoute,
  MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute:
    MainLayoutSpaceSpaceIdRoomRoomIdIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
